config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get'/farmers' => 'pages#farmers'
  get'/chickens_breeds' => 'pages#chickens_breeds'
  get'/profile' => 'pages#profile'
  get'/messages' => 'pages#messages'
  #get "project/new_release" => 'project#new_release', :as => :new_release
  resources :chickens_gangs do
    resources :rentings, only: [:show, :new, :create]
    resources :reviews, only: [:new, :create]

    #atarina
    collection do
      get :my_chicken_gangs
    end

    # Diogo
    collection do
      get :my_bookings
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end


# class Flat
#   belongs_to :owner, class_name: 'User'

app/models/chickens_gang.rb
class ChickensGang < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch
  pg_search_scope :search_by_gang_name_and_breed_and_address,
    against: [ :gang_name, :breed, :address ],
    using: {
      tsearch: { prefix: true }
    }

  has_many :rentings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_many :users, through: :rentings
  belongs_to :owner, class_name: 'User', optional: true

  validates :gang_name, presence: true, uniqueness: true
  validates :breed, presence: true
  validates :capacity, presence: true
  monetize :price_cents

  mount_uploader :photo, PhotoUploader
end

app/models/renting.rb
class Renting < ApplicationRecord
  belongs_to :chickens_gang
  belongs_to :user

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :chickens_gang
  validates :rating, presence: true, inclusion: { in: 0..5}, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rentings

  has_many :chickens_gangs, foreign_key: "owner_id"
  validates :first_name, :last_name, :address, :email, :encrypted_password, presence: true

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery
  before_action :authenticate_user!

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :photo])
  end
end

app/controllers/chickens_gangs_controller.rb
class ChickensGangsController < ApplicationController
  before_action :set_chickens_gang, only: [:show, :destroy, :edit, :update]
  skip_before_action :authenticate_user!, only: [ :index, :show]
  layout "map", only: [:index]

  def index

    @renting = Renting.new
    @chickens_gangs = policy_scope(ChickensGang)
    if params[:query].present?
      @chickens_gangs = ChickensGang.search_by_gang_name_and_breed_and_address(params[:query])
    else
      @chickens_gangs = ChickensGang.all
    end


    @chickens_gangs = @chickens_gangs.where.not(latitude: nil, longitude: nil)
    chickenicon = 'https://s22.postimg.cc/a3r5eegoh/chicken.png';
    @markers = @chickens_gangs.map do |chickens_gang|
      {
        lat: chickens_gang.latitude,
        lng: chickens_gang.longitude,
        icon: chickenicon
        # infoWindow: { content: render_to_string(partial: "/chickens_gangs/map_box", locals: { chickens_gang: chickens_gang }) }
      }

    end
  end

  def show
  end

  def new
    @chickens_gang = ChickensGang.new
    authorize @chickens_gang
  end

  def create
    # add the things in here
    @chickens_gang = ChickensGang.new(chickens_gang_params)
    @chickens_gang = current_user.chickens_gangs.new(chickens_gang_params)
    authorize @chickens_gang
    if @chickens_gang.save
      redirect_to chickens_gangs_path
    else
      render :new
    end

    #raise
  end

  def edit
  end

  def update
    @chickens_gang.update(chickens_gang_params)
    redirect_to chickens_gang_path(@chickens_gang)
  end

  def destroy
    @chickens_gang.destroy
    redirect_to chickens_gangs_path
  end


  def my_chicken_gangs
    @my_chicken_gangs = current_user.chickens_gangs
    @all_rentings = Renting.all
    authorize @all_rentings
  end

  def my_bookings
    @my_bookings = current_user.rentings.order(created_at: :desc)
    authorize @my_bookings
  end

private

  def set_chickens_gang
    @chickens_gang = ChickensGang.find(params[:id])
    authorize @chickens_gang
  end

  def chickens_gang_params
    params.require(:chickens_gang).permit(:gang_name, :address, :breed, :capacity, :year_of_birth, :price, :photo )
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def farmers
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
end

app/controllers/rentings_controller.rb
class RentingsController < ApplicationController
  before_action :set_chickens_gang

  def index
    @rentings = Renting.all
  end

  def show
    @renting = current_user.rentings.where(state: 'paid').find(params[:id])
  end

  def new
    @renting = Renting.new
  end

  def create
    @renting = Order.create!(amount: chickengang.price, state: 'pending', user: current_user)
    @user = current_user.id
    @renting.chickens_gang = @chickens_gang
    @renting.save
    redirect_to chickens_gang_renting_path(@chickens_gang, @renting)
  end

def create
  order  = Order.create!(teddy_sku: teddy.sku, amount: teddy.price, state: 'pending', user: current_user)

  redirect_to new_order_payment_path(order)
end
  private

  def set_chickens_gang
    @chickens_gang = ChickensGang.find(params[:chickens_gang_id])
    authorize @chickens_gang
  end

  def renting_params
    params.require(:renting).permit(:start_date, :end_date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  #before_action :set_review, only: [:show, :destroy, :edit, :update, :booking]
  skip_before_action :authenticate_user!, only: [ :new, :create]
  def new
    @chickens_gang = ChickensGang.find(params[:chickens_gang_id])
    @review = Review.new
    authorize @review
    authorize @chickens_gang
  end

  def create
    @review = Review.new(review_params)
    @chickens_gang = ChickensGang.find(params[:chickens_gang_id])
    @user = current_user.id
    @review.user_id = @user
    @chickens_gang.reviews << @review
    if @review.save
      redirect_to chickens_gang_path(@chickens_gang)
    else
      render :new
    end
    authorize @chickens_gang
    authorize @review
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
    authorize @review
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chickens_gangs/_card.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
  <!-- The whole card is a link to the show page -->
  <%= link_to "", data: {toggle: "modal", target: "#modal-#{chickensgang.id}"} do %>
    <div class="card">
      <!-- If else statement to upload the picture of the chickens gang or the default picture -->
      <% if !chickensgang.photo? %>
        <div class="card-picture"
        style="background-image:
        url('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0yiRaRpABimHCHMw4cXVZKYwK0YjRhGJydn7hzi12WaM_4XknfQ')"></div>
      <% else %>
        <div class="card-picture"
        style="background-image:
        url('<%= cl_image_path chickensgang.photo, crop: :fill %>')"></div>
      <% end %>

      <!-- Section card-body containing name, breed, capacity, price and avatar of the farmer -->
        <div class="card-body">
          <div class="card-description">
            <h2><%= chickensgang.gang_name %></h2>
            <h6><%= chickensgang.breed %></h6>
            <div>
              <p>
                <% chickensgang.capacity.times do %>
                  <%= image_tag "https://visuels.l214.com/animaux/poules/oeufs/oeuf-detoure.png", width: 10, height:15  %>
                <% end %>
                per day
              </p>
              <h4><%= chickensgang.price.round(1)%>€</h4>
            </div>
          </div>

          <!-- If else statement to upload the picture of the farmer gang or the default picture as an avatar -->
          <% if chickensgang.owner.photo.model[:photo] != "https://kitt.lewagon.com/placeholder/users/gittelo"  %>
          <%= cl_image_tag chickensgang.owner.photo, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar card-user" %>
          <% else %>
          <img class="card-user avatar" src="https://kitt.lewagon.com/placeholder/users/gittelo">
          <% end %>
          <p class="card-user-name text-center">Raised by <br>
            <strong><%= chickensgang.owner.first_name  %></strong></p>
<!--             <p>
              <#% chickensgang.review.rating.times do %>
                <#%= image_tag "https://visuels.l214.com/animaux/poules/oeufs/oeuf-detoure.png", width: 10, height:15  %>
              <#% end %>
            </p> -->
        </div>

    </div>
  <% end %>
</div>

   <%= render "modal", chickensgang: chickensgang %>

app/views/chickens_gangs/_form.html.erb
<%= simple_form_for(@chickens_gang) do |f| %>

<div class="col-md-6 col-md-offset-3">
  <div class="form-inputs" style="color: white">
    <%= f.input :gang_name %>
    <%= f.input :address%>
    <%= f.input :breed %>
    <%= f.input :capacity %>
    <%= f.input :year_of_birth %>
    <%= f.input :price %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions flexing-box">
    <%= f.button :submit, class: "btn btn-success" %>
    <%= link_to "Back", chickens_gangs_path, class: "btn btn-danger" %>
  </div>
</div>

<% end %>

app/views/chickens_gangs/_modal.html.erb
<div id="modal-<%= chickensgang.id %>" class="chicken-modal modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <div class="modal-image">

          <% if !chickensgang.photo? %>
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0yiRaRpABimHCHMw4cXVZKYwK0YjRhGJydn7hzi12WaM_4XknfQ">
          <% else %>

          <%= cl_image_tag chickensgang.photo, crop: :fill %>
          <% end %>
        </div>

      </div>
      <div class="modal-description">
        <div class="modal-details">
          <h4> <em><%= chickensgang.gang_name%></em></h4>

          <p> Breed: <%= chickensgang.breed %></p>
          <p> Capacity: <%= chickensgang.capacity %></p>

          <p> Year of birth: <%= chickensgang.year_of_birth %></p>
          <p> Price: <%= chickensgang.price %>€/day</p>

          <p> Available:
            <% if chickensgang.availability %> Yes </p>
            <% else %> No </p>
          <% end %>
        </div>

      </div>
      <div class="modal-reviews">
        <h4>Chickens Gang Reviews</h4>
        <% if !chickensgang.reviews.empty?  %>
          <% average = [] %>
          <% chickensgang.reviews.each do |review| %>
            <% average << review.rating  %>
          <% end %>
          <p> Average rating: <%= (average.reduce(:+)/average.size.to_f).round(1)  %></p>
            <% chickensgang.reviews.each do |review| %>
              <div class="reviews">
                  <div class="reviews-user">
                    <h3><%=review.user.first_name%> <%=review.user.last_name%></h3>
                  </div>
                  <div class="reviews-body">
                    <p><strong>123<%=review.rating%></strong></p>
                    <p>123s<%=review.content%></p>
                  </div>
            <% end %>
              </div>
        <% else %>
          <p>This Chicken Gang has no review yet. </p>
        <% end %>
      </div>
      <div class="modal-booking">

          <%= simple_form_for [chickensgang, @renting] do |f| %>
            <%= f.input :start_date, as: :string %>
            <%= f.input :end_date, as: :string %>
            <%= f.button :submit, 'Book now!', class: "btn btn-danger" %>
          <% end %>

        </div>
      <%= link_to 'Chicken gang details', chickensgang %>
   </div>
  </div>
</div>

app/views/chickens_gangs/_search.html.erb
<%= form_tag chickens_gangs_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a name or breed of a chicken gang"
  %>
<% end %>

app/views/chickens_gangs/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit the Chickens Gang!</h1>
    <%= render "form", chickens_gang: @chickens_gang %>
</div>

app/views/chickens_gangs/index.html.erb
<div class="big-wrapper">

  <div class="results-container">
    <h2>Chickens Gangs around you</h2>
    <div class="row">
      <% @chickens_gangs.each do |chickensgang| %>
        <%= render "card", chickensgang: chickensgang %>
      <% end %>
    </div>
  </div>
  <div id="map" data-markers="<%= @markers.to_json %>">
  </div>
</div>

app/views/chickens_gangs/my_bookings.html.erb
<div class="container">
  <h4 style="text-align: center">My bookings </h4>
  <table class="table">
    <thead>
      <th>Gang Name</th>
      <th>Breed</th>
      <th>Date</th>
      <th>Total Price</th>
      <th>Add a Review</th>
    </thead>
    <tbody>
      <% @my_bookings.each do |booking| %>
        <% start_year =  booking.start_date.strftime('%Y').to_i%>
        <% start_month =  booking.start_date.strftime('%m').to_i%>
        <% start_day =  booking.start_date.strftime('%d').to_i%>
        <% end_year =  booking.end_date.strftime('%Y').to_i%>
        <% end_month =  booking.end_date.strftime('%m').to_i%>
        <% end_day =  booking.end_date.strftime('%d').to_i%>

        <% days = Date.new(end_year, end_month, end_day) -
                  Date.new(start_year, start_month, start_day) %>
        <% chickensgang = booking.chickens_gang %>
        <tr>
          <td><%= chickensgang.gang_name %></td>
          <td><%= chickensgang.breed %></td>
          <td><%= booking.start_date.strftime('%d %b %Y') %> to
              <%= booking.end_date.strftime('%d %b %Y') %></td>
          <td><%= chickensgang.price * days.to_i %>€</td>
          <% if Date.today > booking.end_date %>
            <% if chickensgang.reviews.count == 1 %>
              <td>Review submited</td>
            <% else %>
              <td><%= link_to "+", new_chickens_gang_review_path(booking.chickens_gang_id) %></td>
            <% end %>
          <% else %>
            <td style="color: grey"><em>Review after <%= booking.end_date.strftime('%d %b %Y') %></em></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%#= link_to "+", new_chickens_gang_review_path(booking.chickens_gang_id) %>

app/views/chickens_gangs/my_chicken_gangs.html.erb
<div class="container">
  <h4 style="text-align: center">My Gangs</h4>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Gang Name</th>
      <th scope="col">Breed</th>
      <th scope="col">Capacity</th>
      <th scope="col">Price</th>
      <th scope="col">Manage my Gang</th>
    </tr>
  </thead>

  <tbody>
    <% @my_chicken_gangs.each do |chickengang| %>
      <tr>
        <td><%= chickengang.gang_name %></td>
        <td><%= chickengang.breed %></td>
        <td><%= chickengang.capacity %> eggs/day</td>
        <td><%= chickengang.price %>€/day</td>
        <td><%= link_to "See my gang", chickens_gang_path(chickengang) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h4 style="text-align: center">My Clients</h4>
<table class="table">
  <thead>
    <th>Gang Name</th>
    <th>Booked by</th>
    <th>Date</th>
    <th>Status</th>
  </thead>
  <tbody>
    <% @all_rentings.each do |renting| %>
      <% if renting.chickens_gang.owner == @current_user %>
      <tr>
        <td><%= @my_chicken_gangs.find(renting.chickens_gang_id).gang_name %></td>
        <td><%= renting.user.first_name %></td>
        <td><%= renting.start_date.strftime('%d %b %Y') %> to
            <%= renting.end_date.strftime('%d %b %Y') %></td>
        <% if Date.today < renting.start_date %>
          <td>Booked</td>
        <% elsif Date.today > renting.end_date %>
          <td style="color: orange">Closed</td>
        <% else %>
          <td style="color: green">Active</td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

</div>

app/views/chickens_gangs/new.html.erb
<div class="chicken-wrapper2">
  <div class="container">

    <h1 class="text-center" style="color:white; font-weight: lighter;">New Chickens Gang</h1>
    <%= render "form", chickens_gang: @chickens_gang %>

  </div>
  <hr>
</div>

app/views/chickens_gangs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-9">

      <h3> <%= @chickens_gang.gang_name%>
        <% if current_user == @chickens_gang.owner  %>
          <%= link_to edit_chickens_gang_path(@chickens_gang) do %>
            <i class="fas fa-pencil-alt fa-xs"></i>
          <% end %>
          <%= link_to @chickens_gang, method: :delete, data: {confirm: 'Are you sure?'} do %>
            <i class="fas fa-trash-alt fa-xs"></i>
          <% end %>
        <% end %>
      </h3>

      <p> Breed: <%= @chickens_gang.breed %></p>
      <p> Capacity: <%= @chickens_gang.capacity %></p>

      <p> Year of birth: <%= @chickens_gang.year_of_birth %></p>
      <p> Price: <%= @chickens_gang.price %>€/day</p>

      <p> Available:
        <% if @chickens_gang.availability %> Yes </p>
        <% else %> No </p>
        <% end %>
    </div>



  <div class="row">
    <div class="col-xs-12">
      <h4>Chickens Gang Reviews</h4>

      <% if !@chickens_gang.reviews.empty?  %>
      <% average = [] %>
      <% @chickens_gang.reviews.each do |review| %>
        <% average << review.rating  %>
      <% end %>
      <p> Average rating: <%= (average.reduce(:+)/average.size.to_f).round(1)  %></p>
      <ul>
        <% @chickens_gang.reviews.each do |review| %>
          <li> Comment: <%=review.content%>, Rating: <%=review.rating%> </li>
        <% end %>
      </ul>
      <% else %>
        <p>This Chicken Gang has no review yet. </p>
      <% end %>
    </div>
  </div>

<%= link_to "Back to Chickens Gangs",chickens_gangs_path, class: "btn btn-danger" %>

</div>

 <div class="modal-booking">

          <%= simple_form_for [@chickens_gang, @renting] do |f| %>
            <%= f.input :start_date, as: :string %>
            <%= f.input :end_date, as: :string %>
            <%= f.button :submit, 'Book now!', class: "btn btn-danger" %>
          <% end %>

        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <% unless action_name == "home" || action_name == "farmers" %>
      <%= render 'shared/navbar' %>
    <% end %>
    <% unless action_name == "home" || action_name == "farmers" %>
    <div class="page-wrapper">
    <% end %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
  </body>
</html>

app/views/pages/chickens_breeds.html.erb
<%= render "pages/chicken_breeds" %>

app/views/pages/farmers.html.erb
<div class="banner farmer" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url('https://www.agri-pulse.com/ext/resources/images/Agriculture-photos/Farmscapes/Farm1.jpg?1509734744');">
    <div class="banner-content">
      <h1>Become a farmer</h1>
      <%= link_to "Add your first chicken gang", new_chickens_gang_path, class: 'btn btn-success btn-lg'%>
    </div>
  </div>


  <!-- Messages about why it's cool to join our business -->
  <div class="big-wrapper">
    <div class="container-messages">
      <div class="message">
        <div class="message-picture">
          <img src="https://image.flaticon.com/icons/svg/123/123400.svg" alt="">
        </div>
        <div class="message-content">
          <h3>We take care of the business</h3>
          <p>No need to brush up your marketing skills, or learn accounting. You will not need to worry about any aspect of the business side, just that the eggs are organic.</p>
        </div>
      </div>
      <div class="message">
        <div class="message-picture">
          <img src="https://image.flaticon.com/icons/svg/686/686379.svg" alt="">
        </div>
        <div class="message-content">
          <h3>Get clients</h3>
          <p>You don't have to lose time trying to get new clients. Through Gangs of Chicken, you will get access to thousands of users that will be interested in your product.</p>
        </div>
      </div>
      <div class="message">
        <div class="message-picture">
          <img src="https://image.flaticon.com/icons/svg/189/189093.svg" alt="">
        </div>
        <div class="message-content">
          <h3>Make money</h3>
          <p>We only take a small percentage of the commission :) </p>
        </div>
      </div>
    </div>
  </div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@chickens_gang, @review] do |f| %>
  <div class="form-inputs" style="color: white">
    <%= f.input :rating %>
    <%= f.input :content, :as => :text %>
    <%#= f.button :submit %>
  </div>
  <div class="form-actions flexing-box">
    <%= f.button :submit, "Create Review", class: "btn btn-success" %>
    <%= link_to "Back", @chickens_gang, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_1.jpg", alt: "logo", class: 'avatar' %>
  <% end %>
  <% if action_name == "index"%>
    <%= render "search" %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <!-- If else to know if we display "become a farmer or add a new gang" -->
      <%= link_to "More about breeds", chickens_breeds_path,  class: "navbar-wagon-item navbar-wagon-link" %>|
      <% if current_user.chickens_gangs == [] %>
        <%= link_to "Become a farmer", farmers_path, class: "navbar-wagon-item navbar-wagon-link" %>|
      <% else %>
        <%= link_to "Add a chickens gang", new_chickens_gang_path, class: "navbar-wagon-item navbar-wagon-link" %>|
      <% end %>
      <%= link_to "Messages", messages_path, class: "navbar-wagon-item navbar-wagon-link" %>
    
      <p class="text-center">Welcome <br> <strong><%= current_user.first_name %></strong></p>
      


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <!-- If else to know which avatar to display -->
        <% if current_user.photo.model[:photo] != "https://kitt.lewagon.com/placeholder/users/gittelo"%>
          <%= cl_image_tag current_user.photo, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <%= image_tag current_user.photo.model[:photo], class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>

        <!-- List of tabs in the dropdown list -->
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <!-- Profile -->
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <!-- Settings -->
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <!-- If else to know if we display "My chickens gangs" or "my bookings" -->
            <li>
              <% if current_user.chickens_gangs == [] %>
                <%= link_to my_bookings_chickens_gangs_path do %>
                  <i class="fas fa-kiwi-bird"></i><%= t(".My rentings", default: "My rentings") %>
                <% end %>
              <% else %>
                <%= link_to my_chicken_gangs_chickens_gangs_path do %>
                  <i class="fas fa-kiwi-bird"></i><%= t(".My chickensgangs", default: "My chickensgangs") %>
                <% end %>
                <%= link_to my_bookings_chickens_gangs_path do %>
                  <i class="fas fa-kiwi-bird"></i><%= t(".My rentings", default: "My rentings") %>
                <% end %>
              <% end %>
            </li>
            <!-- Log out -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Become a farmer", farmers_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>